### ISSUE TITLE
Add License Policy info to AboutCode Manager

### ISSUE THREAD

**Issue by majurg** [nexB/aboutcode-manager#139] opened 2017-08-01 17:50 UTC
Per upcoming license policy additions to scancode (see: nexb/scancode-toolkit#214), AboutCode Manager needs to add support for these license policies. 

At the very least, we need the License Policy information to be visible in the table view. Preferably we will have policy information visible in all views; with the node view and/or tree view pointing out license policy finding using color and icon information from AboutCode Data (and DejaCode). 

Additionally, statistics like number of occurrences of policies in scan could be collected and used in reporting (see: #138) and summarization (see: #99) features of AboutCode Manager.

**Comment by jdaguil** [comment] 2018-02-08 01:07
This is a dupe of #215

**Closed by jdaguil** 2018-02-08 01:07 UTC
Labels: enhancement, must have, proposal, ui
