### ISSUE TITLE
Percentage progress indicator will go over 100%

### ISSUE THREAD

**Issue by chinyeungli** [nexB/aboutcode-manager#264] opened 2018-07-19 07:11 UTC
The percentage progress indicator during the import of a large JSON file will show the % is greater than 100%
![over_percentage](https://user-images.githubusercontent.com/4246379/42927112-0276275c-8b66-11e8-8555-23ad1202f802.png)

**Comment by majurg** [comment] 2018-07-19 17:32
Duplicate of #233, closing.

**Closed by majurg** 2018-07-19 17:32 UTC
