### ISSUE TITLE
Filter value not displayed on Windows

### ISSUE THREAD

**Issue by mjherzog** [nexB/aboutcode-manager#227] opened 2018-02-02 01:59 UTC
### Steps to reproduce
1. Select filter on a column - say Filetype value of "C++ source, ASCII text"
2. AbC Mgr shows value in the filter box while processing
3. AbC Mgr displays filtered rows (2 in this case), but filter value disappears from the filter box
4. Select another filter - say "MIT" for License Short Name
5. Abc Mgr applies the filter, but License filter box is blank

**Expected behavior**
Display value of selected filter whenever active (as many characters as allowed by column width

**Actual behavior**
Value of selected filter disappears from the filter box after the filter is applied

**Reproduces how often:** 
100%

### Errors in the Developer Tools
None

[pip-901.zip](https://github.com/nexB/aboutcode-manager/files/1687832/pip-901.zip)

### System configuration
Windows 10
AbC Manager vv2.4.0
ScanCode TK v2.2.1

### Additional Information
Attached SQLite file pip901 (pip v9.0.1)

**Comment by jdaguil** [comment] 2018-02-08 00:01
At the moment, I cannot reproduce this on Mac. I wonder if this is also an issue on Linux. With the file you have provided, I do have the desired behavior

<img width="1438" alt="screen shot 2018-02-07 at 3 48 24 pm" src="https://user-images.githubusercontent.com/4239800/35947815-89560228-0c1e-11e8-9145-c2aaa54c1b96.png">

**Comment by majurg** [comment] 2018-02-08 21:25
Will attempt to reproduce on all platforms

**Comment by majurg** [comment] 2018-02-08 22:05
Can confirm this is an issue on Linux as well. Tested on a vanilla 16.04 desktop.

**Comment by majurg** [comment] 2018-06-27 00:33
#257 fixes this. Closing.

**Closed by majurg** 2018-06-27 00:33 UTC
Labels: bug, must have, windows
